version: "3.8"
services:
  ######################
  ## Discord Producer ##
  ######################
  discord_producer:
    container_name: discord_producer
    build:
      context: ./discord-producer
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    environment:
      LOG_PATH: log/discord-producer.log
      KAFKA_BROKER: "kafka:9093"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      KAFKA_TOPIC: discordmessage
      WAIT_FOR_KAFKA: 10
    volumes:
      - ./log:/app/log

  ###############
  ## Zookeeper ##
  ###############
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    # hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # ALLOW_ANONYMOUS_LOGIN: "yes"

  ###########
  ## Kafka ##
  ###########
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.0
    # hostname: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
